
DROP TABLE IF EXISTS public.media_plan;

CREATE TABLE public.media_plan
(
Agency	 	VARCHAR(300)	,
Client	 	VARCHAR(300)	,
Brand	 	VARCHAR(300)	,
Region	 	VARCHAR(300)	,
Country	 	VARCHAR(300)	,
City	 	VARCHAR(300)	,
Vendor	 	VARCHAR(300)	,
Network_Site	 	VARCHAR(300)	,
Campaign_Initiative	 	VARCHAR(300)	,
Temporality	 	VARCHAR(300)	,
Goal	 	VARCHAR(300)	,
KPI	 	VARCHAR(300)	,
Start_Date	 	DATE	,
End_Date 		DATE	,
URL	 	VARCHAR(300)	,
Device	 	VARCHAR(300)	,
Language	 	VARCHAR(300)	,
Tracking	 	VARCHAR(300)	,
Tag	 	VARCHAR(300)	,
Accountability	 	VARCHAR(300)	,
Currency	 	VARCHAR(300)	,
Total_Cost	 	NUMERIC(50,4)	,
Buy_Type	 	VARCHAR(300)	,
Media_Rate	 	NUMERIC(50,4)	,
Media_Cost	 	NUMERIC(50,4)	,
Media_Units	 	NUMERIC(50,2)	,
Forecast_Impressions	 	NUMERIC(50,4)	,
Forecast_Clicks	 	NUMERIC(50,4)	,
Forecast_Revenue	 	NUMERIC(50,4)	,
KPI_Cost Type	 	VARCHAR(300)	,
KPI_Rate	 	NUMERIC(50,4)	,
KPI_Units	 	NUMERIC(50,4)	,
Section	 	VARCHAR(300)	,
Placement	 	VARCHAR(300)	,
Format_Type	 	VARCHAR(300)	,
Creative_Size	 	VARCHAR(300)	,
Deal_Type	 	VARCHAR(300)	,
"PMP Name"	 	VARCHAR(300)	,
"Adserver Deal type"	 	VARCHAR(300)	,
Adserver	 	VARCHAR(300)	,
"Adserving Type"	 	VARCHAR(300)	,
"Adserver Rate"	 	NUMERIC(50,4)	,
"Adserver Cost"	 	NUMERIC(50,4)	,
"DSP Fee (%)"	 	NUMERIC(50,4)	,
"DSP Fee ($)"	 	NUMERIC(50,4)	,
"Accountability Tool 1 Deal type"	 	VARCHAR(300)	,
"Accountability Tool 1"	 	VARCHAR(300)	,
"Accountability Product 1"	 	VARCHAR(300)	,
"Accountability Rate 1"	 	NUMERIC(50,4)	,
"Accountability Cost 1"	 	NUMERIC(50,4)	,
"Forecast Viewability 1"	 	VARCHAR(300)	,
"Accountability Tool 2 Deal type"	 	VARCHAR(300)	,
"Accountability Tool 2"	 	VARCHAR(300)	,
"Accountability Product 2"	 	VARCHAR(300)	,
"Accountability Rate 2"	 	NUMERIC(50,4)	,
"Accountability Cost 2"	 	NUMERIC(50,4)
);