--POSGRESQL. REMOCION DE DUPLICADOS Y CALCULOS CORRESPONDIENTES A COLUMNAS DE SUMA (totals) Y PROMEDIO (rates).
--CREACIÓN DE UN SUBQUERY "with" POR CADA TIPO DE PLATAFORMA (Facebook/Linkedin/Snapchat/Twitter; Google/Bing, Traditional Display Media).
--CADA UNA DE LAS PLATAFORMA UTILIZA UN GRUPO DE VARIABLES DE AGRUPAMIENTO DIFERENTES
with duplicados_google as (select 
--id 	,
agency	,
client	,
brand	,  
region	,
country	,
max(city) as city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
max(goal) as goal	,
max(kpi) as kpi	,
min(start_date) as start_date	,
max(end_date) as end_date	,
max(url) as url	,
max(device) as device	,
max(language) as language	,
max(tracking) as tracking	,
max(tag) as tag	,
max(accountability) as accountability	,
max(currency) as currency	,
sum(total_cost) as total_cost	,
buy_type	,
avg(media_rate) as media_rate	,
sum(media_cost) as media_cost	,
max(media_units) as media_units	,
sum(forecast_impressions) as forecast_impressions	,
sum(forecast_clicks) as forecast_clicks	,
max(forecast_revenue) as forecast_revenue	,
max(kpi_cost_type) as kpi_rate	,
avg(kpi_rate) as kpi_rate	,
max(kpi_units) as kpi_units	,
max(section) as section	,
max(placement) as placement	,
max(format_type) as format_type	,
max(creative_size) as creative_size	,
max(deal_type) as deal_type	,
max(pmp_name) as pmp_name	,
max(adserver_deal_type) as adserver_deal_type	,
max(adserver) as adserver	,
max(adserving_type) as adserving_type	,
max(adserver_rate) as adserver_rate	,
max(adserver_cost) as adserver_cost	,
max(dsp_fee_percent) as dsp_fee_percent	,
max(dsp_fee_money) as dsp_fee_money	,
max(accountability_tool_1_deal_type) as accountability_tool_1_deal_type	,
max(accountability_tool_1) as accountability_tool_1	,
max(accountability_product_1) as accountability_product_1	,
max(accountability_rate_1) as accountability_rate_1	,
max(accountability_cost_1) as accountability_cost_1	,
max(forecast_viewability_1) as forecast_viewability_1	,
max(accountability_tool_2_deal_type) as accountability_tool_2_deal_type	,
max(accountability_tool_2) as accountability_tool_2	,
max(accountability_product_2) as accountability_product_2	,
max(accountability_rate_2) as accountability_rate_2	,
max(accountability_cost_2) as accountability_cost_2	,
count(*) as contador

from media_plan
where vendor = 'Google' or vendor = 'Bing'
group by 
agency	,
client	,
brand	,
region	,
country	,
--city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
--goal	,
--kpi	,
--start_date	,
--end_date	,
-- url	,
-- device	,
-- language	,
-- tracking	,
-- tag	,
-- accountability	,
-- currency	,
buy_type	
-- media_units	,
-- forecast_revenue	,
-- kpi_cost_type	,
-- kpi_units	,
-- section	,
-- placement	,
-- format_type	,
-- 'creative size'creative_size- deal_type	,
-- pmp_name	,
-- adserver_deal_type	,
-- adserver	,
-- adserving_type	,
-- adserver_rate	,
-- adserver_cost	,
-- dsp_fee_percent	,
-- dsp_fee_money	,
--'accountability	tyability tool 1'	,
--accountability_product_11	,
-- accountability_rate_1	,
-- accountability_cost_1	,
-- forecast_viewability_1	,
-- accountability_tool_2_deal_type	,
-- accountability_tool_2	,
--2'	,
-- accountability_rate_2	,
-- accountability_cost_2	
--having count(*) = 1
--order by
-- agency	,
-- client	,
-- brand	,
-- region	,
-- country	,
-- city	,
-- vendor	,
-- network_site	,
-- campaign_initiative	,
-- temporality	,
-- --goal	,
-- --kpi	,
-- start_date	,
-- end_date	
),

duplicados_facebook as (select 
--id 	,
agency	,
client	,
brand	,
region	,
country	,
max(city) as city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
goal	,
max(kpi) as kpi	,
min(start_date) as start_date	,
max(end_date) as end_date	,
max(url) as url	,
max(device) as device	,
max(language) as language	,
max(tracking) as tracking	,
max(tag) as tag	,
max(accountability) as accountability	,
max(currency) as currency	,
sum(total_cost) as total_cost	,
buy_type	,
avg(media_rate) as media_rate	,
sum(media_cost) as media_cost	,
max(media_units) as media_units	,
sum(forecast_impressions) as forecast_impressions	,
sum(forecast_clicks) as forecast_clicks	,
max(forecast_revenue) as forecast_revenue	,
max(kpi_cost_type) as kpi_rate	,
avg(kpi_rate) as kpi_rate	,
max(kpi_units) as kpi_units	,
max(section) as section	,
max(placement) as placement	,
max(format_type) as format_type	,
max(creative_size) as creative_size	,
max(deal_type) as deal_type	,
max(pmp_name) as pmp_name	,
max(adserver_deal_type) as adserver_deal_type	,
max(adserver) as adserver	,
max(adserving_type) as adserving_type	,
max(adserver_rate) as adserver_rate	,
max(adserver_cost) as adserver_cost	,
max(dsp_fee_percent) as dsp_fee_percent	,
max(dsp_fee_money) as dsp_fee_money	,
max(accountability_tool_1_deal_type) as accountability_tool_1_deal_type	,
max(accountability_tool_1) as accountability_tool_1	,
max(accountability_product_1) as accountability_product_1	,
max(accountability_rate_1) as accountability_rate_1	,
max(accountability_cost_1) as accountability_cost_1	,
max(forecast_viewability_1) as forecast_viewability_1	,
max(accountability_tool_2_deal_type) as accountability_tool_2_deal_type	,
max(accountability_tool_2) as accountability_tool_2	,
max(accountability_product_2) as accountability_product_2	,
max(accountability_rate_2) as accountability_rate_2	,
max(accountability_cost_2) as accountability_cost_2	,
count(*) as contador

from media_plan
where (vendor = 'Facebook' or vendor = 'Linkedin' or vendor = 'Snapchat' or vendor = 'Twitter')
group by 
agency	,
client	,
brand	,
region	,
country	,
--city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
goal	,
--kpi	,
--start_date	,
--end_date	,
-- url	,
-- device	,
-- language	,
-- tracking	,
-- tag	,
-- accountability	,
-- currency	,
buy_type	
-- media_units	,
-- forecast_revenue	,
-- kpi_cost_type	,
-- kpi_units	,
-- section	,
-- placement	,
-- format_type	,
-- 'creative size'creative_size- deal_type	,
-- pmp_name	,
-- adserver_deal_type	,
-- adserver	,
-- adserving_type	,
-- adserver_rate	,
-- adserver_cost	,
-- dsp_fee_percent	,
-- dsp_fee_money	,
-- 'accountability	tyability tool 1'	,
--accountability_product_11	,
-- accountability_rate_1	,
-- accountability_cost_1	,
-- forecast_viewability_1	,
-- accountability_tool_2_deal_type	,
-- accountability_tool_2	,
--2'	,
-- accountability_rate_2	,
-- accountability_cost_2	
--having count(*) = 1
-- order by
-- agency	,
-- client	,
-- brand	,
-- region	,
-- country	,
-- city	,
-- vendor	,
-- network_site	,
-- campaign_initiative	,
-- temporality	,
-- goal	,
-- kpi	,
-- start_date	,
-- end_date	
),

duplicados_display as (select 
--id 	,
agency	,
client	,
brand	,
region	,
country	,
max(city) as city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
max(goal) as goal	,
kpi	,
min(start_date) as start_date	,
max(end_date) as end_date	,
max(url) as url	,
max(device) as device	,
max(language) as language	,
max(tracking) as tracking	,
max(tag) as tag	,
max(accountability) as accountability	,
max(currency) as currency	,
sum(total_cost) as total_cost	,
buy_type	,
avg(media_rate) as media_rate	,
sum(media_cost) as media_cost	,
max(media_units) as media_units	,
sum(forecast_impressions) as forecast_impressions	,
sum(forecast_clicks) as forecast_clicks	,
max(forecast_revenue) as forecast_revenue	,
max(kpi_cost_type) as kpi_rate	,
avg(kpi_rate) as kpi_rate	,
max(kpi_units) as kpi_units	,
max(section) as section	,
max(placement) as placement	,
max(format_type) as format_type	,
max(creative_size) as creative_size	,
max(deal_type) as deal_type	,
max(pmp_name) as pmp_name	,
max(adserver_deal_type) as adserver_deal_type	,
max(adserver) as adserver	,
max(adserving_type) as adserving_type	,
max(adserver_rate) as adserver_rate	,
max(adserver_cost) as adserver_cost	,
max(dsp_fee_percent) as dsp_fee_percent	,
max(dsp_fee_money) as dsp_fee_money	,
max(accountability_tool_1_deal_type) as accountability_tool_1_deal_type	,
max(accountability_tool_1) as accountability_tool_1	,
max(accountability_product_1) as accountability_product_1	,
max(accountability_rate_1) as accountability_rate_1	,
max(accountability_cost_1) as accountability_cost_1	,
max(forecast_viewability_1) as forecast_viewability_1	,
max(accountability_tool_2_deal_type) as accountability_tool_2_deal_type	,
max(accountability_tool_2) as accountability_tool_2	,
max(accountability_product_2) as accountability_product_2	,
max(accountability_rate_2) as accountability_rate_2	,
max(accountability_cost_2) as accountability_cost_2	,
count(*) as contador

from media_plan
where vendor = 'Traditional Display Media' 
group by 
agency	,
client	,
brand	,
region	,
country	,
--city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
--goal	,
kpi	,
--start_date	,
--end_date	,
-- url	,
-- device	,
-- language	,
-- tracking	,
-- tag	,
-- accountability	,
-- currency	,
buy_type	
-- media_units	,
-- forecast_revenue	,
-- kpi_cost_type	,
-- kpi_units	,
-- section	,
-- placement	,
-- format_type	,
-- 'creative size'creative_size- deal_type	,
-- pmp_name	,
-- adserver_deal_type	,
-- adserver	,
-- adserving_type	,
-- adserver_rate	,
-- adserver_cost	,
-- dsp_fee_percent	,
-- dsp_fee_money	,
--  'accountability	tyability tool 1'	,
--accountability_product_11	,
-- accountability_rate_1	,
-- accountability_cost_1	,
-- forecast_viewability_1	,
-- accountability_tool_2_deal_type	,
-- accountability_tool_2	,
--2'	,
-- accountability_rate_2	,
-- accountability_cost_2	
--having count(*) = 1
-- order by
-- agency	,
-- client	,
-- brand	,
-- region	,
-- country	,
-- city	,
-- vendor	,
-- network_site	,
-- campaign_initiative	,
-- temporality	,
-- goal	,
-- kpi	,
-- start_date	,
-- end_date	
)

--APPEND PARA CREAR UN UNICO QUERY EN BASE A LOS RESULTADOS ARROJADOS ANTERIORMENTE:
select *
from duplicados_google
union all
select *
from duplicados_facebook
union all
select *
from duplicados_display
order by
agency	,
client	,
brand	,
region	,
country	,
city	,
vendor	,
network_site	,
campaign_initiative	,
temporality	,
goal	,
kpi	,
--start_date	,
--end_date	,
url	,
device	,
language	,
tracking	,
tag	,
accountability	,
currency	,
total_cost	,
buy_type	
